import { describe, it, before, after } from 'node:test';
import assert from 'node:assert';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { init, AI_CONFIGS, SUPPORTED_AI, buildPrompt, loadDataset } from '../src/init.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const tmpDir = path.join(__dirname, '.tmp-test');

const EXPECTED_FILES = {
  claude: '.claude/skills/fingerprint/SKILL.md',
  codex: '.agents/skills/fingerprint/SKILL.md',
  cursor: '.cursor/skills/fingerprint/SKILL.md',
  copilot: '.github/prompts/fingerprint.prompt.md',
  windsurf: '.windsurf/workflows/fingerprint.md',
  cline: '.cline/skills/fingerprint/SKILL.md',
  kiro: '.kiro/skills/fingerprint/SKILL.md',
  augment: '.augment/commands/fingerprint.md',
  trae: '.trae/commands/fingerprint.md',
  opencode: '.opencode/commands/fingerprint.md',
  qwen: '.qwen/commands/fingerprint.md',
  roo: '.roo/commands/fingerprint.md',
  antigravity: '.agents/skills/fingerprint/SKILL.md',
  gemini: '.gemini/commands/fingerprint.toml'
};

async function runInit(opts) {
  const originalExit = process.exit;
  const originalLog = console.log;
  const originalErr = console.error;
  const originalWarn = console.warn;
  const logs = [];
  process.exit = (code) => { throw new Error(`process.exit(${code})`); };
  console.log = console.error = console.warn = (...a) => logs.push(a.join(' '));
  try {
    await init(opts);
  } finally {
    process.exit = originalExit;
    console.log = originalLog;
    console.error = originalErr;
    console.warn = originalWarn;
  }
  return logs.join('\n');
}

describe('ccfp init', () => {
  before(() => {
    fs.rmSync(tmpDir, { recursive: true, force: true });
    fs.mkdirSync(tmpDir, { recursive: true });
  });
  after(() => fs.rmSync(tmpDir, { recursive: true, force: true }));

  it('covers every supported assistant', () => {
    assert.deepStrictEqual(Object.keys(EXPECTED_FILES).sort(), [...SUPPORTED_AI].sort());
  });

  for (const ai of SUPPORTED_AI) {
    for (const lang of ['zh', 'en']) {
      it(`generates the /fingerprint file for ${ai} (${lang})`, async () => {
        const outputDir = path.join(tmpDir, `${ai}-${lang}`);
        await runInit({ ai, output: outputDir, lang });
        const file = path.join(outputDir, EXPECTED_FILES[ai]);
        assert.ok(fs.existsSync(file), `File should exist: ${file}`);
        const content = fs.readFileSync(file, 'utf-8');
        assert.ok(content.includes('ccfp verify'), 'prompt must tell the model to run ccfp verify');
        assert.ok(content.includes('generated by ccfingerprint'), 'generated files carry a marker');
        if (AI_CONFIGS[ai].format === 'skill') {
          assert.match(content, /^---\nname: fingerprint\ndescription: .+\ndisable-model-invocation: true\n---/);
        }
        if (AI_CONFIGS[ai].format === 'toml') {
          assert.match(content, /^# .*\ndescription = ".+"\nprompt = '''\n/);
          assert.ok(content.trimEnd().endsWith("'''"));
        }
      });
    }
  }

  it('codex gets an openai.yaml that keeps the skill explicit-only', async () => {
    const outputDir = path.join(tmpDir, 'codex-yaml');
    await runInit({ ai: 'codex', output: outputDir, lang: 'en' });
    const yaml = fs.readFileSync(path.join(outputDir, '.agents/skills/fingerprint/agents/openai.yaml'), 'utf-8');
    assert.ok(yaml.includes('allow_implicit_invocation: false'));
  });

  it('--ai all installs every target once', async () => {
    const outputDir = path.join(tmpDir, 'all');
    await runInit({ ai: 'all', output: outputDir, lang: 'en' });
    for (const rel of new Set(Object.values(EXPECTED_FILES))) {
      assert.ok(fs.existsSync(path.join(outputDir, rel)), rel);
    }
  });

  it('never overwrites a file it did not generate unless --force', async () => {
    const outputDir = path.join(tmpDir, 'protect');
    const file = path.join(outputDir, EXPECTED_FILES.augment);
    fs.mkdirSync(path.dirname(file), { recursive: true });
    fs.writeFileSync(file, 'my own command');
    await assert.rejects(runInit({ ai: 'augment', output: outputDir, lang: 'en' }), /process\.exit\(1\)/);
    assert.strictEqual(fs.readFileSync(file, 'utf-8'), 'my own command');
    await runInit({ ai: 'augment', output: outputDir, lang: 'en', force: true });
    assert.ok(fs.readFileSync(file, 'utf-8').includes('ccfp verify'));
    // regenerating our own file is allowed without --force
    await runInit({ ai: 'augment', output: outputDir, lang: 'zh' });
  });

  it('warns about always-on copies left by older versions', async () => {
    const outputDir = path.join(tmpDir, 'legacy');
    fs.mkdirSync(outputDir, { recursive: true });
    fs.writeFileSync(path.join(outputDir, 'AGENTS.md'), '# old\nrun ccfp verify ccfp-report.json');
    const logs = await runInit({ ai: 'claude', output: outputDir, lang: 'en' });
    assert.ok(logs.includes('AGENTS.md'), logs);
  });

  it('rejects unknown assistants', async () => {
    await assert.rejects(runInit({ ai: 'nope', output: tmpDir, lang: 'en' }), /process\.exit\(1\)/);
  });

  it('keeps the Windsurf workflow under its 12,000-character limit', () => {
    const dataset = loadDataset();
    for (const lang of ['zh', 'en']) {
      assert.ok(buildPrompt('windsurf', lang, dataset).length < 12000);
    }
  });
});
